name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: laptop  # Using your local runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

    
      - name: secret test
        run: echo "${{ secrets.GH_TOKEN }}"
      