on:
  workflow_dispatch:
    inputs:
      yaml_content:
        description: "Paste YAML content here as a single string"
        required: true
        type: string

jobs:
  push_formatted_yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install PyYAML
        run: pip install pyyaml

      - name: Save input YAML to a temporary file
        run: echo "${{ inputs.yaml_content }}" > input.yaml

      - name: Run formatting script
        run: python formating.py
        env:
          INPUT_FILE: input.yaml
          OUTPUT_FILE: temp.yaml

      - name: Commit and push formatted YAML
        run: |
          git add temp.yaml
          git commit -m "Add formatted YAML file from workflow"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}
