name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: laptop  # Using your local runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if GH_TOKEN is set
        run: echo "GH_TOKEN is: $GH_TOKEN"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t cicdtest .

      - name: Run Docker container
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Pass the token to the job environment
        run: |
          docker run -e GH_TOKEN=$GH_TOKEN cicdtest  # Pass the token into the container
